# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiMainA2SRC.ui'
#
# Created: Wed Jan 07 16:36:01 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 60, 271, 371))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.labelModulation = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelModulation.sizePolicy().hasHeightForWidth())
        self.labelModulation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelModulation.setFont(font)
        self.labelModulation.setObjectName(_fromUtf8("labelModulation"))
        self.verticalLayout.addWidget(self.labelModulation)
        self.comboBoxModulationType = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBoxModulationType.setEditable(False)
        self.comboBoxModulationType.setObjectName(_fromUtf8("comboBoxModulationType"))
        self.comboBoxModulationType.addItem(_fromUtf8(""))
        self.comboBoxModulationType.addItem(_fromUtf8(""))
        self.comboBoxModulationType.addItem(_fromUtf8(""))
        self.comboBoxModulationType.addItem(_fromUtf8(""))
        self.comboBoxModulationType.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.comboBoxModulationType)
        self.checkBoxModulationPhase = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxModulationPhase.setChecked(True)
        self.checkBoxModulationPhase.setObjectName(_fromUtf8("checkBoxModulationPhase"))
        self.verticalLayout.addWidget(self.checkBoxModulationPhase)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEditModulationFreq = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEditModulationFreq.setObjectName(_fromUtf8("lineEditModulationFreq"))
        self.horizontalLayout.addWidget(self.lineEditModulationFreq)
        self.labelModulationFreq = QtGui.QLabel(self.verticalLayoutWidget)
        self.labelModulationFreq.setObjectName(_fromUtf8("labelModulationFreq"))
        self.horizontalLayout.addWidget(self.labelModulationFreq)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEditModulationAmp = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEditModulationAmp.setObjectName(_fromUtf8("lineEditModulationAmp"))
        self.horizontalLayout_2.addWidget(self.lineEditModulationAmp)
        self.labelModulationAmp = QtGui.QLabel(self.verticalLayoutWidget)
        self.labelModulationAmp.setObjectName(_fromUtf8("labelModulationAmp"))
        self.horizontalLayout_2.addWidget(self.labelModulationAmp)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelSynth = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSynth.sizePolicy().hasHeightForWidth())
        self.labelSynth.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelSynth.setFont(font)
        self.labelSynth.setObjectName(_fromUtf8("labelSynth"))
        self.verticalLayout_2.addWidget(self.labelSynth)
        self.comboBoxSynthType = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBoxSynthType.setEditable(False)
        self.comboBoxSynthType.setObjectName(_fromUtf8("comboBoxSynthType"))
        self.verticalLayout_2.addWidget(self.comboBoxSynthType)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineEditSynthFreq = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEditSynthFreq.setObjectName(_fromUtf8("lineEditSynthFreq"))
        self.horizontalLayout_3.addWidget(self.lineEditSynthFreq)
        self.labelSynthFreq = QtGui.QLabel(self.verticalLayoutWidget)
        self.labelSynthFreq.setObjectName(_fromUtf8("labelSynthFreq"))
        self.horizontalLayout_3.addWidget(self.labelSynthFreq)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEditSynthAmp = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEditSynthAmp.setObjectName(_fromUtf8("lineEditSynthAmp"))
        self.horizontalLayout_4.addWidget(self.lineEditSynthAmp)
        self.labelSynthAmp = QtGui.QLabel(self.verticalLayoutWidget)
        self.labelSynthAmp.setObjectName(_fromUtf8("labelSynthAmp"))
        self.horizontalLayout_4.addWidget(self.labelSynthAmp)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checkBoxPlotEnable = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxPlotEnable.setObjectName(_fromUtf8("checkBoxPlotEnable"))
        self.horizontalLayout_6.addWidget(self.checkBoxPlotEnable)
        self.checkBoxPlotJitter = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxPlotJitter.setObjectName(_fromUtf8("checkBoxPlotJitter"))
        self.horizontalLayout_6.addWidget(self.checkBoxPlotJitter)
        self.checkBoxPlotError = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxPlotError.setObjectName(_fromUtf8("checkBoxPlotError"))
        self.horizontalLayout_6.addWidget(self.checkBoxPlotError)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButtonPlot = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButtonPlot.setObjectName(_fromUtf8("pushButtonPlot"))
        self.horizontalLayout_7.addWidget(self.pushButtonPlot)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButtonOpenFile = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButtonOpenFile.setObjectName(_fromUtf8("pushButtonOpenFile"))
        self.horizontalLayout_5.addWidget(self.pushButtonOpenFile)
        self.pushButtonStart = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButtonStart.setObjectName(_fromUtf8("pushButtonStart"))
        self.horizontalLayout_5.addWidget(self.pushButtonStart)
        self.pushButtonStop = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButtonStop.setObjectName(_fromUtf8("pushButtonStop"))
        self.horizontalLayout_5.addWidget(self.pushButtonStop)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.matplotlibwidget = MatplotlibWidget(self.centralwidget)
        self.matplotlibwidget.setGeometry(QtCore.QRect(320, 60, 451, 371))
        self.matplotlibwidget.setObjectName(_fromUtf8("matplotlibwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelModulation.setText(_translate("MainWindow", "Jitter Modulation", None))
        self.comboBoxModulationType.setItemText(0, _translate("MainWindow", "None", None))
        self.comboBoxModulationType.setItemText(1, _translate("MainWindow", "Sinusoidal", None))
        self.comboBoxModulationType.setItemText(2, _translate("MainWindow", "Triangular", None))
        self.comboBoxModulationType.setItemText(3, _translate("MainWindow", "Rectangular", None))
        self.comboBoxModulationType.setItemText(4, _translate("MainWindow", "Random", None))
        self.checkBoxModulationPhase.setText(_translate("MainWindow", "Modulation R / L in-phase", None))
        self.lineEditModulationFreq.setText(_translate("MainWindow", "50", None))
        self.labelModulationFreq.setText(_translate("MainWindow", " Hz", None))
        self.lineEditModulationAmp.setText(_translate("MainWindow", "1e-3", None))
        self.labelModulationAmp.setText(_translate("MainWindow", " UI", None))
        self.labelSynth.setText(_translate("MainWindow", "Synthetic Signal", None))
        self.lineEditSynthFreq.setText(_translate("MainWindow", "1000", None))
        self.labelSynthFreq.setText(_translate("MainWindow", " Hz", None))
        self.lineEditSynthAmp.setText(_translate("MainWindow", "50", None))
        self.labelSynthAmp.setText(_translate("MainWindow", "% FS", None))
        self.checkBoxPlotEnable.setText(_translate("MainWindow", "Enable Plot", None))
        self.checkBoxPlotJitter.setText(_translate("MainWindow", "Plot Jitter", None))
        self.checkBoxPlotError.setText(_translate("MainWindow", "Plot Error", None))
        self.pushButtonPlot.setText(_translate("MainWindow", "Plot NOW", None))
        self.pushButtonOpenFile.setText(_translate("MainWindow", "Open File", None))
        self.pushButtonStart.setText(_translate("MainWindow", "Start", None))
        self.pushButtonStop.setText(_translate("MainWindow", "Stop", None))

from matplotlibwidget import MatplotlibWidget
