# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_a2src.ui'
#
# Created: Tue May 12 13:47:23 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1021, 837)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1001, 776))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelSynth = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSynth.sizePolicy().hasHeightForWidth())
        self.labelSynth.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelSynth.setFont(font)
        self.labelSynth.setObjectName(_fromUtf8("labelSynth"))
        self.verticalLayout_2.addWidget(self.labelSynth)
        self.comboBoxInputType = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxInputType.setEditable(False)
        self.comboBoxInputType.setObjectName(_fromUtf8("comboBoxInputType"))
        self.comboBoxInputType.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.comboBoxInputType)
        self.labelAudioIn = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAudioIn.sizePolicy().hasHeightForWidth())
        self.labelAudioIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelAudioIn.setFont(font)
        self.labelAudioIn.setObjectName(_fromUtf8("labelAudioIn"))
        self.verticalLayout_2.addWidget(self.labelAudioIn)
        self.comboBoxAudioIn = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxAudioIn.setObjectName(_fromUtf8("comboBoxAudioIn"))
        self.verticalLayout_2.addWidget(self.comboBoxAudioIn)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButtonOpenReadFile = QtGui.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOpenReadFile.setFont(font)
        self.pushButtonOpenReadFile.setObjectName(_fromUtf8("pushButtonOpenReadFile"))
        self.horizontalLayout_2.addWidget(self.pushButtonOpenReadFile)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.labelAudioIn_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAudioIn_3.sizePolicy().hasHeightForWidth())
        self.labelAudioIn_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelAudioIn_3.setFont(font)
        self.labelAudioIn_3.setObjectName(_fromUtf8("labelAudioIn_3"))
        self.verticalLayout_2.addWidget(self.labelAudioIn_3)
        self.comboBoxSignalType = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxSignalType.setEditable(False)
        self.comboBoxSignalType.setObjectName(_fromUtf8("comboBoxSignalType"))
        self.comboBoxSignalType.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.comboBoxSignalType)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineEditSynthFreq = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditSynthFreq.setObjectName(_fromUtf8("lineEditSynthFreq"))
        self.horizontalLayout_3.addWidget(self.lineEditSynthFreq)
        self.labelSynthFreq = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.labelSynthFreq.setObjectName(_fromUtf8("labelSynthFreq"))
        self.horizontalLayout_3.addWidget(self.labelSynthFreq)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEditSynthAmp = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditSynthAmp.setObjectName(_fromUtf8("lineEditSynthAmp"))
        self.horizontalLayout_4.addWidget(self.lineEditSynthAmp)
        self.labelSynthAmp = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.labelSynthAmp.setObjectName(_fromUtf8("labelSynthAmp"))
        self.horizontalLayout_4.addWidget(self.labelSynthAmp)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.labelModulation = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelModulation.sizePolicy().hasHeightForWidth())
        self.labelModulation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelModulation.setFont(font)
        self.labelModulation.setObjectName(_fromUtf8("labelModulation"))
        self.horizontalLayout_9.addWidget(self.labelModulation)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.checkBoxEnableModulation = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBoxEnableModulation.setObjectName(_fromUtf8("checkBoxEnableModulation"))
        self.horizontalLayout_9.addWidget(self.checkBoxEnableModulation)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEditModulationFreq = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditModulationFreq.setObjectName(_fromUtf8("lineEditModulationFreq"))
        self.gridLayout_2.addWidget(self.lineEditModulationFreq, 1, 1, 1, 1)
        self.labelModulationAmp = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.labelModulationAmp.setObjectName(_fromUtf8("labelModulationAmp"))
        self.gridLayout_2.addWidget(self.labelModulationAmp, 2, 2, 1, 1)
        self.labelModulationFreq = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.labelModulationFreq.setObjectName(_fromUtf8("labelModulationFreq"))
        self.gridLayout_2.addWidget(self.labelModulationFreq, 1, 2, 1, 1)
        self.lineEditModulationAmp = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditModulationAmp.setObjectName(_fromUtf8("lineEditModulationAmp"))
        self.gridLayout_2.addWidget(self.lineEditModulationAmp, 2, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 1, 1, 1)
        self.comboBoxModulationType = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxModulationType.setEditable(False)
        self.comboBoxModulationType.setObjectName(_fromUtf8("comboBoxModulationType"))
        self.comboBoxModulationType.addItem(_fromUtf8(""))
        self.comboBoxModulationType.addItem(_fromUtf8(""))
        self.comboBoxModulationType.addItem(_fromUtf8(""))
        self.comboBoxModulationType.addItem(_fromUtf8(""))
        self.comboBoxModulationType.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBoxModulationType, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.checkBoxModulationPhase = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBoxModulationPhase.setObjectName(_fromUtf8("checkBoxModulationPhase"))
        self.gridLayout_2.addWidget(self.checkBoxModulationPhase, 0, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.labelAudioOut = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAudioOut.sizePolicy().hasHeightForWidth())
        self.labelAudioOut.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelAudioOut.setFont(font)
        self.labelAudioOut.setObjectName(_fromUtf8("labelAudioOut"))
        self.verticalLayout.addWidget(self.labelAudioOut)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checkBoxEnableStreamOut = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBoxEnableStreamOut.setObjectName(_fromUtf8("checkBoxEnableStreamOut"))
        self.horizontalLayout_6.addWidget(self.checkBoxEnableStreamOut)
        self.checkBoxEnableFileWrite = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBoxEnableFileWrite.setObjectName(_fromUtf8("checkBoxEnableFileWrite"))
        self.horizontalLayout_6.addWidget(self.checkBoxEnableFileWrite)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButtonOpenWriteFile = QtGui.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOpenWriteFile.setFont(font)
        self.pushButtonOpenWriteFile.setObjectName(_fromUtf8("pushButtonOpenWriteFile"))
        self.horizontalLayout_5.addWidget(self.pushButtonOpenWriteFile)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.comboBoxAudioOut = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxAudioOut.setObjectName(_fromUtf8("comboBoxAudioOut"))
        self.verticalLayout.addWidget(self.comboBoxAudioOut)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pushButtonStart = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonStart.setObjectName(_fromUtf8("pushButtonStart"))
        self.horizontalLayout_10.addWidget(self.pushButtonStart)
        self.pushButtonStop = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonStop.setCheckable(True)
        self.pushButtonStop.setObjectName(_fromUtf8("pushButtonStop"))
        self.horizontalLayout_10.addWidget(self.pushButtonStop)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_24.addLayout(self.verticalLayout)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.qwtPlot = Qwt5.QwtPlot(self.scrollAreaWidgetContents)
        self.qwtPlot.setObjectName(_fromUtf8("qwtPlot"))
        self.verticalLayout_11.addWidget(self.qwtPlot)
        self.matplotlibwidget_2 = MatplotlibWidget(self.scrollAreaWidgetContents)
        self.matplotlibwidget_2.setObjectName(_fromUtf8("matplotlibwidget_2"))
        self.verticalLayout_11.addWidget(self.matplotlibwidget_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.labelSynth_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSynth_2.sizePolicy().hasHeightForWidth())
        self.labelSynth_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelSynth_2.setFont(font)
        self.labelSynth_2.setObjectName(_fromUtf8("labelSynth_2"))
        self.verticalLayout_4.addWidget(self.labelSynth_2)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.checkBoxPlotEnable = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBoxPlotEnable.setObjectName(_fromUtf8("checkBoxPlotEnable"))
        self.horizontalLayout_12.addWidget(self.checkBoxPlotEnable)
        self.checkBoxPlotJitter = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBoxPlotJitter.setObjectName(_fromUtf8("checkBoxPlotJitter"))
        self.horizontalLayout_12.addWidget(self.checkBoxPlotJitter)
        self.checkBoxPlotError = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBoxPlotError.setObjectName(_fromUtf8("checkBoxPlotError"))
        self.horizontalLayout_12.addWidget(self.checkBoxPlotError)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.pushButtonPlot = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonPlot.setObjectName(_fromUtf8("pushButtonPlot"))
        self.horizontalLayout_13.addWidget(self.pushButtonPlot)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.verticalLayout_11.addLayout(self.verticalLayout_4)
        self.horizontalLayout_24.addLayout(self.verticalLayout_11)
        self.gridLayout_3.addLayout(self.horizontalLayout_24, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1021, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelSynth.setText(_translate("MainWindow", "Input Signal", None))
        self.comboBoxInputType.setItemText(0, _translate("MainWindow", "WAV-File", None))
        self.labelAudioIn.setText(_translate("MainWindow", "Audio Input Source", None))
        self.pushButtonOpenReadFile.setText(_translate("MainWindow", "Read Audio File", None))
        self.label_3.setText(_translate("MainWindow", "AudioFileName", None))
        self.label_5.setText(_translate("MainWindow", "Word Length: ", None))
        self.label_6.setText(_translate("MainWindow", "24", None))
        self.label_7.setText(_translate("MainWindow", "NChan: ", None))
        self.label_8.setText(_translate("MainWindow", "2", None))
        self.labelAudioIn_3.setText(_translate("MainWindow", "Synthetic Data", None))
        self.comboBoxSignalType.setItemText(0, _translate("MainWindow", "Sinusoidal", None))
        self.lineEditSynthFreq.setText(_translate("MainWindow", "1000", None))
        self.labelSynthFreq.setText(_translate("MainWindow", " Hz", None))
        self.lineEditSynthAmp.setText(_translate("MainWindow", "50", None))
        self.labelSynthAmp.setText(_translate("MainWindow", "% FS", None))
        self.labelModulation.setText(_translate("MainWindow", "Jitter Modulation", None))
        self.checkBoxEnableModulation.setText(_translate("MainWindow", "Enable", None))
        self.lineEditModulationFreq.setText(_translate("MainWindow", "50", None))
        self.labelModulationAmp.setText(_translate("MainWindow", " UI", None))
        self.labelModulationFreq.setText(_translate("MainWindow", " Hz", None))
        self.lineEditModulationAmp.setText(_translate("MainWindow", "1e-3", None))
        self.comboBoxModulationType.setItemText(0, _translate("MainWindow", "None", None))
        self.comboBoxModulationType.setItemText(1, _translate("MainWindow", "Sinusoidal", None))
        self.comboBoxModulationType.setItemText(2, _translate("MainWindow", "Triangular", None))
        self.comboBoxModulationType.setItemText(3, _translate("MainWindow", "Rectangular", None))
        self.comboBoxModulationType.setItemText(4, _translate("MainWindow", "Random", None))
        self.label.setText(_translate("MainWindow", "Amplitude", None))
        self.label_2.setText(_translate("MainWindow", "Frequency", None))
        self.checkBoxModulationPhase.setText(_translate("MainWindow", "R/L In-Phase", None))
        self.labelAudioOut.setText(_translate("MainWindow", "Audio Output Source", None))
        self.checkBoxEnableStreamOut.setText(_translate("MainWindow", "Stream Out", None))
        self.checkBoxEnableFileWrite.setText(_translate("MainWindow", "File Write", None))
        self.pushButtonOpenWriteFile.setText(_translate("MainWindow", "Write Audio File", None))
        self.label_4.setText(_translate("MainWindow", "AudioFileName", None))
        self.pushButtonStart.setText(_translate("MainWindow", "Start", None))
        self.pushButtonStop.setText(_translate("MainWindow", "Stop", None))
        self.labelSynth_2.setText(_translate("MainWindow", "Plotting", None))
        self.checkBoxPlotEnable.setText(_translate("MainWindow", "Enable Plot", None))
        self.checkBoxPlotJitter.setText(_translate("MainWindow", "Plot Jitter", None))
        self.checkBoxPlotError.setText(_translate("MainWindow", "Plot Error", None))
        self.pushButtonPlot.setText(_translate("MainWindow", "Plot NOW", None))

from PyQt4 import Qwt5
from matplotlibwidget import MatplotlibWidget
